name: blazeGrids CI/CD

on:
  push:
    branches: [ master ]

jobs:
  deploy:
      name: Deployment
      runs-on: ubuntu-latest
      steps:
        # - uses: actions/checkout@v2
        #   with:
        #     ref: master

        # - name: Set Up Node
        #   uses: actions/setup-node@v1
        #   with:
        #     node-version: "19.x"
        # - run: yarn
        # - run: yarn production

        - name: Deploy to server
          uses: easingthemes/ssh-deploy@v4.1.8
          env:
            SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY }}
            ARGS: "-rltgoDzvO --exclude .git --exclude .docker --exclude .github node_modules .bladeformatterrc.json"
            REMOTE_HOST: ${{ secrets.SSH_HOST }}
            REMOTE_USER: ${{ secrets.SSH_USER }}
            TARGET: /home/defaultwebsite/blazeGrids

        # - name: Execute commands SSH
        #   uses: appleboy/ssh-action@master
        #   with:
        #     host: ${{ secrets.SSH_HOST }}
        #     username: ${{ secrets.SSH_USER }}
        #     port: ${{ secrets.SSH_PORT }}
        #     key: ${{ secrets.SSH_KEY }}
        #     passphrase: ${{ secrets.SSH_PASSPHRASE }}
        #     script: |
        #       php artisan optimize
        #       composer dump auto-load -o