name: Laravel CI/CD

on:
  push:
    branches: [ master ]

jobs:
  deploy:
      name: Deployment
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
          with:
            ref: master

        # - name: Deploy to server
        #   uses: easingthemes/ssh-deploy@v2.2.11
        #   env:
        #     SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        #     ARGS: "-rltgoDzvO --exclude .git --exclude .docker --exclude .github"
        #     REMOTE_HOST: ${{ secrets.SSH_HOST }}
        #     REMOTE_USER: ${{ secrets.SSH_USER }}
        #     TARGET: /home/${{ secrets.SSH_USER }}/ci-cd

        # - name: Execute comands SSH
        #   uses: appleboy/ssh-action@master
        #   env:
        #     USER_PASS: "${{ secrets.USER_PASS }}"
        #   with:
        #     host: ${{ secrets.SSH_HOST }}
        #     username: ${{ secrets.SSH_USER }}
        #     key: ${{ secrets.SSH_PRIVATE_KEY }}
        #     port: ${{ secrets.SSH_PORT }}
        #     envs: USER_PASS
        #     script: |
        #       cd ci-cd/
        #       echo $USER_PASS | sudo -S docker-compose up -d
        #       echo $USER_PASS | sudo -S docker-compose exec -T curso_api_cache composer install
        #       echo $USER_PASS | sudo -S docker-compose exec -T curso_api_cache php artisan migrate --force